name: Create a Tag on master branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

# Controls when the action will run.
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tagging:
    name: Tagging
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Set version name to github env
        run: |
          echo "version_name=$(${{github.workspace}}/gradlew -q printVersionName)" >> $GITHUB_ENV
      - name: Get latest tag
        id: latestTag
        uses: oprypin/find-latest-tag@v1.1.0
        with:
          repository: phamvanducdev/ComposeUI
          # releases-only: false  # This repository doesn't use GitHub's "release" feature.
      - name: Set version code to github env
        run: |
          LATEST_TAG_NAME=${{ steps.latestTag.outputs.tag }}
          CURRENT_VERSION_CODE=`echo ${LATEST_TAG_NAME} | sed -e "s/v.*\-//"`
          INCREMENTED_VERSION_CODE=`expr $CURRENT_VERSION_CODE + 1`

          echo "version_code=${INCREMENTED_VERSION_CODE}" >> $GITHUB_ENV
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.version_name }}-${{ env.version_code }}
          tag_prefix: v
          release_branches: master
  call-build-release-production:
    needs: [ tagging ]
    uses: ./.github/workflows/build_production.yml
    secrets: inherit
    with:
      tag: ${{ needs.tagging.outputs.new_tag }}
